pipeline {
    agent any
    environment {
        PATH = "D:\apache-maven-3.9.5\apache-maven\src\bin$PATH"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('build') {
            steps {
                checkout scm
            }
        }
  }
}
